### PR TITLE
Create CLI

### LINKED ISSUE #21: CLI for adding structures
Make a CLI for adding a structure. Streamlines the contribution process by creating a skeleton for the structure.

### PR DESCRIPTION
**Pull request by Matt-Gleich**
## Description

Create a CLI to automate the process of adding structures to standard-structure

## Related Issue

This PR resolves #21 

## Motivation and Context

The current method of adding structures isn't very scalable and is really repetitive.

## Types of changes

- [ ] New framework or language
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the structure and style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] There is no duplicate pull request for this fix/addition/issue resolution.
- [x] If applicable, my code passes all current tests, and passes new tests that I have written to test it if the current tests do not suffice.

### CODE REVIEW

**Comment by sampoder** [comment]
🎉 Looks good!

**Comment by Matt-Gleich** [comment]
Good idea. I will add that right now

**Comment by Matt-Gleich** [comment]
@sampoder 
It would be great if you could add it. I've gotta go to bed.

**Comment by sampoder** [comment]
K, sure I'll look into after this piece of homework

**Comment by Matt-Gleich** [comment]
Ok, thank you!

**Pull request merged**
