### PR TITLE
Feature/refactor framework structure

### LINKED ISSUE #19: Better variance support
I propose updating the folder structure for frameworks to something like this:

```
frameworks/
|- {name}/
   |- index.md
   |- {variant-name}/
```

This allows for a lot more flexibility in frameworks, and solves the issue of different types of structures.

### PR DESCRIPTION
**Pull request by rishiosaur**
Closes #19 for the Flask template system.

### CODE REVIEW

**Comment by rishiosaur** [comment]
You got it!

**Comment by rishiosaur** [comment]
@Matt-Gleich take a look! I updated all the READMEs as well.

**Comment by rishiosaur** [comment]
This also begs the question: should we have a CLI just to make a structure

**Comment by Matt-Gleich** [comment]
I was thinking the same thing, make another issue to we can discuss it there.

**Comment by rishiosaur** [comment]
Is this good to merge?

**Pull request merged**
